version: "3.7"

services:
  elasticsearch:
    environment:
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    environment:
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    ports:
      - 5601:5601
    #   - "127.0.0.1:5601:5601"
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: pangff@feawin.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:   
       
networks:
  default:
    name: $DEFAULT_NETWORK
