version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: "true"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/localtime:/etc/localtime:ro

  kibana:
    image: kibana:$ELK_VERSION
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
  
  metricbeat_system:
    image: docker.elastic.co/beats/metricbeat:$ELK_VERSION
    container_name: metricbeat-elasticserver
    user: root
    network_mode: "host"
    volumes:
      - ./metricbeat-elasticserver/ilm.json:/usr/share/metricbeat/ilm.json:ro
      - ./metricbeat-elasticserver/config.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      # ELASTICSEARCH_USERNAME: $ELASTIC_USER
      # ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    depends_on:
      - elasticsearch
  
  apm:
    image: docker.elastic.co/apm/apm-server:$ELK_VERSION
    container_name: apm
    command: --strict.perms=false -e
    ports:
      - "8200:8200"
    environment:
      ELASTICSEARCH_HOSTS: "http://localhost:9200"
    # volumes:
    #   - "./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    depends_on:
      - elasticsearch

networks:
  default:
    name: $DEFAULT_NETWORK
