version: "3.7"

services:
  simple_logger:
    build:
      context: ./simple-logger
    image: simple-logger
    container_name: simple-logger
  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat
    user: root
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./filebeat/ilm.json:/usr/share/filebeat/ilm.json:ro
      - ./filebeat/fields.yml:/usr/share/filebeat/custom.yml:ro
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      ELASTICSEARCH_HOSTS: $ELASTIC_SERVER_HOST:9200
      KIBANA_HOST: $ELASTIC_SERVER_HOST:5601
      # ELASTICSEARCH_USERNAME: $ELASTIC_USER
      # ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-e"]
    restart: on-failure
